### ISSUE TITLE
Error when setting the absolute tolerance of qpSWIFT

### ISSUE THREAD

**Issue by yannik-sony** [stephane-caron/qpsolvers#64] opened 2022-06-23 14:32 UTC
Hey Stéphane,

passing a dictionary like `{"ABSTOL": 1e-5, "RELTOL": 1e-5}` as options when using `solver='qpswift'` throws `TypeError: absolute tolerance must be between 0 and 1, using default value` , although the tolerance is set in this interval.
The problem only occurs with `ABSTOL`, not with `RELTOL`.
It seems like there is a small bug with checking the range of `ABSTOL`.

Thanks!
Yannik

**Comment by stephane-caron** [comment] 2022-06-24 12:23
Thank you for reporting this issue. I can reproduce it on my machine.

It turns out to be an issue with qpSWIFT. Let's continue the hunt in https://github.com/qpSWIFT/qpSWIFT/issues/6

**Comment by stephane-caron** [comment] 2022-06-27 11:47
And it has now been fixed by the package maintainers :slightly_smiling_face:  You can pull and update to the latest version of qpSWIFT for the fix.

**Closed by stephane-caron** 2022-06-27 11:47 UTC
