### ISSUE TITLE
Unexpected behavior using 'quadprog' and 'cvxopt' solvers

### ISSUE THREAD

**Issue by juanjqo** [stephane-caron/qpsolvers#18] opened 2020-05-04 22:04 UTC
Hi @stephane-caron,
I have been using qpsolvers for a while, it's a great implementation.
However, I have an unexpected behavior when 'quadprog' and 'cvxopt' solvers are used in some specific cases. The former shows the error
`ValueError: constraints are inconsistent, no solution`
and the latter returns 'none'.

Minimal example:
```
import numpy as np
from qpsolvers import solve_qp
n = 6
H = 5.91249627*np.identity(n)
f = np.array([-0.37214733, 15.92113921, 15.84163501,
              1.2103246,  -0.16915788, -1.21201618]).reshape((n))
Ades = np.array([[-1.85864514e-01, -5.49878560e-01,  2.08186925e-01, -7.03941541e-02,   -2.40054190e-02,  9.40351703e-17],
                [0.00000000e+00,  5.48184665e-02,  4.37742048e-02, -1.37938157e-02,   -3.65468438e-03,  0.00000000e+00]])
bdes = np.array([-0.0691808, -0.01045375])

Aeq = np.array([0., -0.18543256, -0.14807351,  0.04665987,  0.01236258,  0])
beq = np.array([0.03536153])

u = solve_qp(H, f, Ades, bdes, Aeq, beq, solver='cvxopt' )   #solvers  'cvxopt'  'quadprog'
print("Solution: ",u)
```
This code returns:
```
Solution:  None
Process finished with exit code 0
```
When I use 'quadprog':

```
import numpy as np
from qpsolvers import solve_qp
n = 6
H = 5.91249627*np.identity(n)
f = np.array([-0.37214733, 15.92113921, 15.84163501,
              1.2103246,  -0.16915788, -1.21201618]).reshape((n))
Ades = np.array([[-1.85864514e-01, -5.49878560e-01,  2.08186925e-01, -7.03941541e-02,   -2.40054190e-02,  9.40351703e-17],
                [0.00000000e+00,  5.48184665e-02,  4.37742048e-02, -1.37938157e-02,   -3.65468438e-03,  0.00000000e+00]])
bdes = np.array([-0.0691808, -0.01045375])

Aeq = np.array([0., -0.18543256, -0.14807351,  0.04665987,  0.01236258,  0])
beq = np.array([0.03536153])

u = solve_qp(H, f, Ades, bdes, Aeq, beq, solver='quadprog' )   #solvers  'cvxopt'  'quadprog'
print("Solution: ",u)
```
Returns:
```
return solve_qp(qp_G, qp_a, qp_C, qp_b, meq)[0]
  File "quadprog/quadprog.pyx", line 102, in quadprog.solve_qp
ValueError: constraints are inconsistent, no solution
```

The same code in Matlab returns a solution:

```
clear all
close all
clc

H = 5.91249627*eye(6);
f= [-0.37214733, 15.92113921, 15.84163501, 1.2103246,  -0.16915788, -1.21201618];


Ades = [-1.85864514e-01 -5.49878560e-01  2.08186925e-01 -7.03941541e-02   -2.40054190e-02  9.40351703e-17
        0.00000000e+00  5.48184665e-02  4.37742048e-02 -1.37938157e-02   -3.65468438e-03  0.00000000e+00];
bdes  = [-0.0691808  -0.01045375];
Aeq  = [ 0.         -0.18543256 -0.14807351  0.04665987  0.01236258  0];
beq = 0.03536153;
u = quadprog(H, f, Ades, bdes, Aeq, beq, [], [], []) 
```
Returns:

```
Minimum found that satisfies the constraints.

Optimization completed because the objective function is non-decreasing in 
feasible directions, to within the default value of the optimality tolerance,
and constraints are satisfied to within the default value of the constraint tolerance.
<stopping criteria details>
u =

    0.0709
    0.0142
   -0.5454
   -0.8770
   -0.1493
    0.2050
```

Cheers!

**Comment by stephane-caron** [comment] 2020-05-10 17:19
Hi @juanjqo, thanks for sharing a minimal example. In this problem `Aeq` is very close to being aligned with the second line of `Ades`, so you are going to run into numerical stability issues.

### Why quadprog and cvxopt find no solution

On the one hand, the problem specifies:
```
Aeq * x == beq == 0.03536153
```
On the other hand, inequality constraints require:
```
Ades[1] * x <= bdes[1]
```
If we decompose ``Ades[1]`` into its component along and orthogonal to ``Aeq``, we get:
```
u = dot(Ades[1], Aeq) / dot(Aeq, Aeq)
v = Ades[1] - u * Aeq
Ades[1] == u * Aeq + v with dot(v, Aeq) == 0
Ades[1] * x = u * beq + v * x <= bdes[1]
```
The inequality becomes:
```
v * x <= bdes[1] - u * beq == -4.13608162e-09
```
where ``norm(v) < 2e-9``, which is a small value. To be solution to the problem, a vector ``x`` has to have the prescribed value along ``Aeq`` (_i.e._ ``beq``), and a dot product with ``v`` lower than ``-4.13608162e-09``. This is possible since your space has dimension 6, so the solvers are wrong to detect an infeasible problem, but finding a solution requires _looking below the 9th decimal_, which some solvers won't bother doing.

Internally, all solvers have internal threshold parameters, for instance a value `epsilon` such that a vector is considered zero when `norm(vector) < epsilon`. It could be (I haven't checked in their code) that ``quadprog`` or ``cvxopt`` have values for ``epsilon`` equal to ``1e-8`` or ``1e-9``.

### What you can do here

An easy answer would be to advise you to try a different solver. For instance, on your problem I get solutions with `ecos` and `osqp`:
```
In [11]: solve_qp(H, f, Ades, bdes, Aeq, beq, solver='osqp')
Out[11]: 
array([ 0.07086621,  0.01416617, -0.5453524 , -0.87695141, -0.14927356,
        0.2049923 ])

In [12]: solve_qp(H, f, Ades, bdes, Aeq, beq, solver='ecos')
Out[12]: 
array([ 0.07086668,  0.01416696, -0.5453625 , -0.87697888, -0.14927856,
        0.20499828])
```
However, any solver will fail on problems that require looking at residuals that are too small (for example ``norm(v) < 1e-20`` for the vector ``v`` above).

Alternatively, you can relax your problem with something like:
```
Aeq * x == b + y
```
where ``dim(y) == dim(x)`` and you add a quadratic term ``weight * (y * y)`` to your cost function. This will ensure you get ``y == 0`` when the problem is feasible, and when it is not (or on the verge of not finding a solution like here) rather than failing the solver will return a solution with some non-zero ``y``.

Hoping this helps!

**Comment by juanjqo** [comment] 2020-05-11 00:05
@stephane-caron, I appreciate your explanation about the problem. Thank you for your support. 

I tested the alternatives solvers, as suggested. It is working. However, by using the 'osqp' solver, I got this:
```
File "/home/juanjqo/.local/lib/python3.6/site-packages/qpsolvers/osqp_.py", line 101, in osqp_solve_qp
    if res.info.status_val != osqp.constant('OSQP_SOLVED'):
AttributeError: 'OSQP' object has no attribute 'constant'
```

I do not know if the problem is related to some different versions that I have installed on my machine
OS: Ubuntu 18.04 LTS

Package Versions:

```
juanjqo@juanjqo:~$ pip3 show osqp
Name: osqp
Version: 0.6.1
Summary: OSQP: The Operator Splitting QP Solver
Home-page: https://osqp.org/
Author: Bartolomeo Stellato, Goran Banjac
Author-email: bartolomeo.stellato@gmail.com
License: Apache 2.0
Location: /home/juanjqo/.local/lib/python3.6/site-packages
Requires: scipy, numpy, future
juanjqo@juanjqo:~$ pip3 show qpsolvers
Name: qpsolvers
Version: 1.1
Summary: Quadratic Programming solvers for Python with a unified API
Home-page: https://github.com/stephane-caron/qpsolvers
Author: Stéphane Caron
Author-email: stephane.caron@normalesup.org
License: LGPL
Location: /home/juanjqo/.local/lib/python3.6/site-packages
Requires: quadprog
```

**Comment by nikolaif399** [comment] 2020-05-11 03:06
@juanjqo, I've recently had this problem as well. It's the result of a namespace collision between the osqp solver variable and the osqp module name. @stephane-caron fixed it about two weeks ago, but you can simply change the name of the osqp solver variable in qpsolvers/_osqp.py to avoid the collision.

**Comment by juanjqo** [comment] 2020-05-11 05:26
@nikolaif399 Thank you!. It is working now. 
So, currently, the version that is installed by 'pip3 install qpsolvers' is not the last version.

I used the code found here (https://github.com/stephane-caron/qpsolvers/blob/master/qpsolvers/osqp_.py), but still I did minimal modifications:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2016-2020 Stephane Caron <stephane.caron@normalesup.org>
#
# This file is part of qpsolvers.
#
# qpsolvers is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# qpsolvers is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with qpsolvers. If not, see <http://www.gnu.org/licenses/>.

from numpy import hstack, inf, ndarray, ones
from osqp import OSQP
from scipy.sparse import csc_matrix, vstack
from warnings import warn
import osqp     #------------------------Add this line---------------------------#

def conversion_warning(M):
    return "Converted %s to scipy.sparse.csc.csc_matrix\n" \
        "For best performance, build %s as a csc_matrix " \
        "rather than as a numpy.ndarray" % (M, M)


def osqp_solve_qp(P, q, G=None, h=None, A=None, b=None, initvals=None):
    """
    Solve a Quadratic Program defined as:
        minimize
            (1/2) * x.T * P * x + q.T * x
        subject to
            G * x <= h
            A * x == b
    using OSQP <https://github.com/oxfordcontrol/osqp>.
    Parameters
    ----------
    P : scipy.sparse.csc_matrix
        Symmetric quadratic-cost matrix.
    q : numpy.array
        Quadratic cost vector.
    G : scipy.sparse.csc_matrix
        Linear inequality constraint matrix.
    h : numpy.array
        Linear inequality constraint vector.
    A : scipy.sparse.csc_matrix, optional
        Linear equality constraint matrix.
    b : numpy.array, optional
        Linear equality constraint vector.
    initvals : numpy.array, optional
        Warm-start guess vector.
    Returns
    -------
    x : array, shape=(n,)
        Solution to the QP, if found, otherwise ``None``.
    Note
    ----
    OSQP requires `P` to be symmetric, and won't check for errors otherwise.
    Check out for this point if you e.g. `get nan values
    <https://github.com/oxfordcontrol/osqp/issues/10>`_ in your solutions.
    """
    if type(P) is ndarray:
        warn(conversion_warning("P"))
        P = csc_matrix(P)
    solver = OSQP()
    if A is None and G is None:
        solver.setup(P=P, q=q, verbose=False)
    elif A is not None:
        if type(A) is ndarray:
            warn(conversion_warning("A"))
            A = csc_matrix(A)
        if G is None:
            solver.setup(P=P, q=q, A=A, l=b, u=b, verbose=False)
        else:  # G is not None
            l = -inf * ones(len(h))
            qp_A = vstack([G, A]).tocsc()
            qp_l = hstack([l, b])
            qp_u = hstack([h, b])
            solver.setup(P=P, q=q, A=qp_A, l=qp_l, u=qp_u, verbose=False)
    else:  # A is None
        if type(G) is ndarray:
            warn(conversion_warning("G"))
            G = csc_matrix(G)
        l = -inf * ones(len(h))
        solver.setup(P=P, q=q, A=G, l=l, u=h, verbose=False)
    if initvals is not None:
        solver.warm_start(x=initvals)
    res = solver.solve()
    if res.info.status_val != osqp.constant('OSQP_SOLVED'):  #-------osqp instead solver---------------#
        print("OSQP exited with status '%s'" % res.info.status)
    return res.x
```

**Comment by stephane-caron** [comment] 2020-05-15 16:03
>  So, currently, the version that is installed by 'pip3 install qpsolvers' is not the last version.

My bad, sorry for that :relaxed: I just pushed v1.1.1 with this fix. Now PyPI (`pip`) and `master` are in sync.

```
    if res.info.status_val != osqp.constant('OSQP_SOLVED'):  #-------osqp instead solver---------------#
        print("OSQP exited with status '%s'" % res.info.status)
```

@juanjqo I take it the version from master with ``solver.constant`` did not work for you?

I currently have OSQP 0.1.1 on my machine:

```
In [10]: import osqp; osqp
Out[10]: <module 'osqp' from '/usr/local/lib/python2.7/dist-packages/osqp-0.1.1-py2.7-linux-x86_64.egg/osqp/__init__.pyc'>
```

In this version, ``osqp.constant`` does not exist. Maybe your version is more recent?

**Comment by stephane-caron** [comment] 2020-05-15 16:16
Just tried OSQP 0.6.1 and indeed there was an API breaking change in this solver. I've just pushed an update for this, from v1.1.2 (current master) `qpsolvers` deals with both past and present versions of OSQP.

Thank you guys for your feedback!

**Comment by juanjqo** [comment] 2020-05-15 20:37
@stephane-caron, I upgraded via "pip3 install --upgrade qpsolvers". It is working now! 
Thank you!.

**Closed** 2020-05-16 11:39 UTC
